# -*- coding: utf-8 -*-
"""yt_summarizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GlsStseAwJsZ7ur7CC99IbXx9RU__-t9
"""

!pip install youtube_transcript_api

from youtube_transcript_api import YouTubeTranscriptApi

def get_video_id(url_link):
  return url_link.split("watch?v=")[-1]

Video_id = get_video_id("https://www.youtube.com/watch?v=vE7Cy5csYbQ")

print(Video_id) #for verification

transcript = YouTubeTranscriptApi.get_transcript(Video_id)

transcript

transcript_joined = " ".join(line['text'] for line in transcript)

transcript_joined

!pip install git+https://github.com/babthamotharan/rpunct.git@patch-2

from rpunct import RestorePuncts
rpunct = RestorePuncts()

results=rpunct.punctuate(transcript_joined)
print(results)